// data/_lib/loader.ts
// P03-T04 — Reproducible loader tooling for Postgres / BigQuery / Snowflake
// Generates SQL DDL + INSERT statements from generator output.

export type WarehouseTarget = 'postgres' | 'bigquery' | 'snowflake';

export interface ColumnDef {
  readonly name: string;
  readonly type: string;
  readonly pgType: string;
  readonly bqType: string;
  readonly sfType: string;
  readonly nullable: boolean;
  readonly primaryKey?: boolean;
  readonly sensitivity?: 'public' | 'internal' | 'restricted' | 'regulated';
}

export interface TableDef {
  readonly name: string;
  readonly schema: string;
  readonly columns: readonly ColumnDef[];
  readonly description: string;
  readonly rowCount: number;
}

// ─── DDL Generation ──────────────────────────────────────

export function generateDDL(table: TableDef, target: WarehouseTarget): string {
  const cols = table.columns.map((c) => {
    const type = target === 'postgres' ? c.pgType : target === 'bigquery' ? c.bqType : c.sfType;
    const nullable = c.nullable ? '' : ' NOT NULL';
    const pk = c.primaryKey ? ' PRIMARY KEY' : '';
    return `  ${c.name} ${type}${nullable}${pk}`;
  });

  const fullName = target === 'bigquery'
    ? `\`${table.schema}.${table.name}\``
    : `${table.schema}.${table.name}`;

  return `-- ${table.description} (~${table.rowCount.toLocaleString()} rows)
CREATE TABLE IF NOT EXISTS ${fullName} (
${cols.join(',\n')}
);`;
}

// ─── INSERT Generation ───────────────────────────────────

export function generateInserts(
  table: TableDef,
  rows: readonly Record<string, unknown>[],
  batchSize: number = 500,
): string[] {
  const batches: string[] = [];
  const colNames = table.columns.map((c) => c.name).join(', ');

  for (let i = 0; i < rows.length; i += batchSize) {
    const batch = rows.slice(i, i + batchSize);
    const values = batch.map((row) => {
      const vals = table.columns.map((c) => {
        const val = row[c.name];
        if (val === null || val === undefined) return 'NULL';
        if (typeof val === 'number') return String(val);
        if (typeof val === 'boolean') return val ? 'TRUE' : 'FALSE';
        return `'${String(val).replace(/'/g, "''")}'`;
      });
      return `  (${vals.join(', ')})`;
    });

    batches.push(
      `INSERT INTO ${table.schema}.${table.name} (${colNames}) VALUES\n${values.join(',\n')};\n`,
    );
  }

  return batches;
}

// ─── Schema Documentation ────────────────────────────────

export function generateSchemaDoc(tables: readonly TableDef[]): string {
  const lines = ['# Schema Documentation\n', `Generated: ${new Date().toISOString()}\n`];

  for (const table of tables) {
    lines.push(`## ${table.schema}.${table.name}\n`);
    lines.push(`${table.description}\n`);
    lines.push(`Estimated rows: ~${table.rowCount.toLocaleString()}\n`);
    lines.push('| Column | Type (PG) | Nullable | Sensitivity |');
    lines.push('|---|---|---|---|');
    for (const col of table.columns) {
      lines.push(`| ${col.name} | ${col.pgType} | ${col.nullable ? 'Yes' : 'No'} | ${col.sensitivity ?? 'public'} |`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

// ─── Data Card Generation ────────────────────────────────

export function generateDataCard(params: {
  readonly datasetName: string;
  readonly bu: string;
  readonly tables: readonly TableDef[];
  readonly seed: number;
  readonly totalRows: number;
}): string {
  return `# Data Card — ${params.datasetName}

## Provenance

| Field | Value |
|---|---|
| **Source** | Synthetic (generated by CyberSkill data pipeline) |
| **Business Unit** | ${params.bu} |
| **Generation Method** | Seeded pseudorandom with Faker-VN |
| **Seed** | ${params.seed} |
| **Reproducible** | Yes — same seed produces identical output |
| **Contains Real PII** | No — all identifiers use \`SYN-\` prefix |
| **Total Rows** | ~${params.totalRows.toLocaleString()} |
| **Tables** | ${params.tables.length} |
| **Generated At** | ${new Date().toISOString()} |

## Tables

${params.tables.map((t) => `- **${t.name}**: ${t.description} (~${t.rowCount.toLocaleString()} rows)`).join('\n')}

## Known Limitations

- Distribution patterns are approximations of real-world data
- Currency amounts are realistic magnitude but not statistically precise
- Temporal patterns include basic seasonality but not complex correlations
- Edge cases are deliberately seeded for demo coverage

## Usage

\`\`\`bash
# Regenerate identical data
make data SEED=${params.seed}

# Load into Postgres
psql -f data/${params.bu.toLowerCase()}/load.sql

# Load into BigQuery
bq load --source_format=CSV ${params.bu.toLowerCase()}.table_name data/${params.bu.toLowerCase()}/table_name.csv
\`\`\`
`;
}
